import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import { useState } from 'react';  // Import useState
import styles from '@/styles/Home.module.css';
import { getTagDescription } from '../data/data';
import SearchBar from '../components/SearchBar';

const inter = Inter({ subsets: ['latin'] });

const formatDescription = (description) => {
  const segments = description.split('(\n');
  const formattedDescription = segments.map((segment, index) => (
    <div key={index}>
      <p>{segment.trim()}</p>
    </div>
  ));
  return formattedDescription;
};


export default function Home() {
  const [searchResults, setSearchResults] = useState(null);  // Define searchResults state

  const handleSearch = (query) => {
    // Use getTagDescription to get the description based on the query
    //const description = getTagDescription(query);
  
    // Update your page content or log the description
    console.log('Search query:', query.tag);
    console.log('Description:', query.description);

    // Update searchResults state
    setSearchResults(query);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`flex min-h-screen flex-col items-center justify-center p-24 ${styles.main} ${inter.className}`} style={{ backgroundColor: 'black' }}>
        <div className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="fixed top-8 left-1/2 transform -translate-x-1/2 flex place-items-center gap-2 p-8">
            <Image
              src="/zmd.svg"
              alt="zmd Logo"
              className="dark:invert"
              width={540}
              height={111}
              priority
            />
          </div>
          
          <SearchBar
            onSearch={handleSearch}
            placeholder="Search your disease"
            // Add any additional styling or props for highlighting
          />
          
          {/* Display search results */}
          {searchResults && (
            <div className="mt-4" style={{ color: 'white' }}>
              {/*<h2>Search Results</h2>*/}
              <p>Disease found: {searchResults.tag}</p>
              <div className="grid grid-cols-2 gap-4">
                {formatDescription(searchResults.description)}
              <p>{searchResults.description}</p>
              </div>
            </div>
          )}

          {/* Additional content goes here */}
        </div>
      </main>
    </>
  );
}
