import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import SearchBar from '../components/SearchBar'; // Assuming the correct path to SearchBar

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const handleSearch = (query) => {
    // Implement your search logic here based on the query
    console.log('Search query:', query);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`flex min-h-screen flex-col items-center justify-center p-24 ${styles.main} ${inter.className}`} style={{ backgroundColor: 'black' }}>
        <div className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="fixed top-8 left-1/2 transform -translate-x-1/2 flex place-items-center gap-2 p-8">
            <Image
              src="/zmd.svg"
              alt="zmd Logo"
              className="dark:invert"
              width={540}
              height={111}
              priority
            />
          </div>
          
          <SearchBar
            onSearch={handleSearch}
            placeholder="Search your disease"
            // Add any additional styling or props for highlighting
          />
        </div>

        {/* Additional content goes here */}
      </main>
    </>
  );
}
